version: "3"
services:
  db:
    image: postgres
    build: ./database
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  eureka-serviceregistry:
    build: ./service-discovery
    ports:
      - "8761:8761"
    tty: true
    depends_on:
      - db
      - rabbitmq-broker
      - axon-server

  axon-server:
    image: axoniq/axonserver:4.3.2
    ports:
      - 8024:8024
      - 8124:8124

  agent:
    build: ./agent
    ports:
      - "8091:8091"
    environment:
      - POSTGRES_DB=agent
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    tty: true
    depends_on:
      - db

  account-service:
    build: ./account-service
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_SCHEMA=account_schema
      - AXON_HOST=axon-server
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - rabbitmq-broker
      - axon-server

  agent-service:
    build: ./agent-service
    ports:
      - "8081:8081"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_SCHEMA=agent_schema
      - RQM_HOST=rabbitmq-broker
      - RMQ_PORT=5672
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - rabbitmq-broker
      - axon-server

  catalog-service:
    build: ./catalog-service
    ports:
      - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_SCHEMA=catalog_schema
      - RQM_HOST=rabbitmq-broker
      - RMQ_PORT=5672
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - rabbitmq-broker
      - axon-server

  renting-service:
    build: ./renting-service
    ports:
      - "8086:8086"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_SCHEMA=renting_schema
      - AXON_HOST=axon-server
      - RQM_HOST=rabbitmq-broker
      - RMQ_PORT=5672
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - rabbitmq-broker
      - axon-server

  view-service:
    build: ./view-service
    ports:
      - "8087:8087"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_SCHEMA=view_schema
      - RQM_HOST=rabbitmq-broker
      - RMQ_PORT=5672
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - rabbitmq-broker
      - axon-server

  search-service:
    build: ./search-service
    ports:
      - "8088:8088"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_SCHEMA=search_schema
      - RQM_HOST=rabbitmq-broker
      - RMQ_PORT=5672
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - rabbitmq-broker
      - axon-server

  message-service:
    build: ./message-service
    ports:
      - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - POSTGRES_DB=service-db
      - POSTGRES_DOMAIN=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_SCHEMA=message_schema
      - RQM_HOST=rabbitmq-broker
      - RQM_PORT=5672
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - rabbitmq-broker
      - axon-server

  zuul:
    build: ./gateway
    ports:
      - "8089:8089"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - db
      - eureka-serviceregistry
      - account-service
      - agent-service
      - catalog-service
      - renting-service
      - search-service
      - view-service
      - rabbitmq-broker
      - axon-server

  rabbitmq-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
