version: '3'
services:

  eureka-serviceregistry:
    build: ./service-discovery
    ports:
      - "8761:8761"
    tty: true

  account-service:
    build: ./account-service
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

 zuul:
    build: ./gateway
    ports:
      - "8089:8089"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - account-service




