spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:eureka-serviceregistry}

server:
  port: 8761
  ssl:
    enabled: true
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    key-store: classpath:${KEYSTORE:eureka.keystore.p12}
    key-store-password: ${KEYSTORE_PASSWORD:password}
    key-alias: ${KEYSTORE_ALIAS:eureka}
    trust-store: classpath:${TRUSTSTORE:eureka.truststore.p12}
    trust-store-password: ${TRUSTSTORE_PASSWORD:password}
    client-auth: need


eureka:
  instance:
    hostname: ${springboot.app.name:eureka-serviceregistry}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${registry.host:localhost}:${server.port}/eureka/


logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF