//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 02:58:30 PM CEST 

package rs.ac.uns.ftn.catalog;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.catalog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.catalog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewAdvertisementRequest }
     * 
     */
    public NewAdvertisementRequest createNewAdvertisementRequest() {
        return new NewAdvertisementRequest();
    }

    /**
     * Create an instance of {@link Advertisement }
     * 
     */
    public Advertisement createAdvertisement() {
        return new Advertisement();
    }

    /**
     * Create an instance of {@link NewAdvertisementResponse }
     * 
     */
    public NewAdvertisementResponse createNewAdvertisementResponse() {
        return new NewAdvertisementResponse();
    }

    /**
     * Create an instance of {@link NewPhotoRequest }
     * 
     */
    public NewPhotoRequest createNewPhotoRequest() {
        return new NewPhotoRequest();
    }

    /**
     * Create an instance of {@link CommentRequest }
     * 
     */
    public CommentRequest createCommentRequest() {
        return new CommentRequest();
    }

    /**
     * Create an instance of {@link NewPhotoResponse }
     * 
     */
    public NewPhotoResponse createNewPhotoResponse() {
        return new NewPhotoResponse();
    }

    /**
     * Create an instance of {@link NewRentingIntervalRequest }
     * 
     */
    public NewRentingIntervalRequest createNewRentingIntervalRequest() {
        return new NewRentingIntervalRequest();
    }

    /**
     * Create an instance of {@link RentingInterval }
     * 
     */
    public RentingInterval createRentingInterval() {
        return new RentingInterval();
    }

    /**
     * Create an instance of {@link NewRentingIntervalResponse }
     * 
     */
    public NewRentingIntervalResponse createNewRentingIntervalResponse() {
        return new NewRentingIntervalResponse();
    }

    /**
     * Create an instance of {@link CommentResponse }
     * 
     */
    public CommentResponse createCommentResponse() {
        return new CommentResponse();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link UpdateAdvertisementRequest }
     * 
     */
    public UpdateAdvertisementRequest createUpdateAdvertisementRequest() {
        return new UpdateAdvertisementRequest();
    }

    /**
     * Create an instance of {@link UpdateAdvertisementResponse }
     * 
     */
    public UpdateAdvertisementResponse createUpdateAdvertisementResponse() {
        return new UpdateAdvertisementResponse();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementRequest }
     * 
     */
    public DeleteAdvertisementRequest createDeleteAdvertisementRequest() {
        return new DeleteAdvertisementRequest();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementResponse }
     * 
     */
    public DeleteAdvertisementResponse createDeleteAdvertisementResponse() {
        return new DeleteAdvertisementResponse();
    }

    /**
     * Create an instance of {@link PriceRequest }
     * 
     */
    public PriceRequest createPriceRequest() {
        return new PriceRequest();
    }

    /**
     * Create an instance of {@link PriceListItem }
     * 
     */
    public PriceListItem createPriceListItem() {
        return new PriceListItem();
    }

    /**
     * Create an instance of {@link PriceResponse }
     * 
     */
    public PriceResponse createPriceResponse() {
        return new PriceResponse();
    }

    /**
     * Create an instance of {@link NewCommentRequest }
     * 
     */
    public NewCommentRequest createNewCommentRequest() {
        return new NewCommentRequest();
    }

    /**
     * Create an instance of {@link NewCommentResponse }
     * 
     */
    public NewCommentResponse createNewCommentResponse() {
        return new NewCommentResponse();
    }

    /**
     * Create an instance of {@link NewDiscountRequest }
     * 
     */
    public NewDiscountRequest createNewDiscountRequest() {
        return new NewDiscountRequest();
    }

    /**
     * Create an instance of {@link NewDiscountResponse }
     * 
     */
    public NewDiscountResponse createNewDiscountResponse() {
        return new NewDiscountResponse();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link GetCatalogRequest }
     * 
     */
    public GetCatalogRequest createGetCatalogRequest() {
        return new GetCatalogRequest();
    }

    /**
     * Create an instance of {@link GetCatalogResponse }
     * 
     */
    public GetCatalogResponse createGetCatalogResponse() {
        return new GetCatalogResponse();
    }

    /**
     * Create an instance of {@link Brand }
     * 
     */
    public Brand createBrand() {
        return new Brand();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link FuelType }
     * 
     */
    public FuelType createFuelType() {
        return new FuelType();
    }

    /**
     * Create an instance of {@link GearboxType }
     * 
     */
    public GearboxType createGearboxType() {
        return new GearboxType();
    }

    /**
     * Create an instance of {@link VehicleClass }
     * 
     */
    public VehicleClass createVehicleClass() {
        return new VehicleClass();
    }

    /**
     * Create an instance of {@link MessageRequest }
     * 
     */
    public MessageRequest createMessageRequest() {
        return new MessageRequest();
    }

    /**
     * Create an instance of {@link MessageResponse }
     * 
     */
    public MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

    /**
     * Create an instance of {@link Chat }
     * 
     */
    public Chat createChat() {
        return new Chat();
    }

    /**
     * Create an instance of {@link NewMessageRequest }
     * 
     */
    public NewMessageRequest createNewMessageRequest() {
        return new NewMessageRequest();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link NewMessageResponse }
     * 
     */
    public NewMessageResponse createNewMessageResponse() {
        return new NewMessageResponse();
    }

    /**
     * Create an instance of {@link DeleteMessageRequest }
     * 
     */
    public DeleteMessageRequest createDeleteMessageRequest() {
        return new DeleteMessageRequest();
    }

    /**
     * Create an instance of {@link DeleteMessageResponse }
     * 
     */
    public DeleteMessageResponse createDeleteMessageResponse() {
        return new DeleteMessageResponse();
    }

    /**
     * Create an instance of {@link GetFinishedRequest }
     * 
     */
    public GetFinishedRequest createGetFinishedRequest() {
        return new GetFinishedRequest();
    }

    /**
     * Create an instance of {@link GetFinishedResponse }
     * 
     */
    public GetFinishedResponse createGetFinishedResponse() {
        return new GetFinishedResponse();
    }

    /**
     * Create an instance of {@link FinishedRequest }
     * 
     */
    public FinishedRequest createFinishedRequest() {
        return new FinishedRequest();
    }

    /**
     * Create an instance of {@link CompileReportRequest }
     * 
     */
    public CompileReportRequest createCompileReportRequest() {
        return new CompileReportRequest();
    }

    /**
     * Create an instance of {@link CompileReportResponse }
     * 
     */
    public CompileReportResponse createCompileReportResponse() {
        return new CompileReportResponse();
    }

    /**
     * Create an instance of {@link PendingRentingRequestResponse }
     * 
     */
    public PendingRentingRequestResponse createPendingRentingRequestResponse() {
        return new PendingRentingRequestResponse();
    }

    /**
     * Create an instance of {@link PendingRequest }
     * 
     */
    public PendingRequest createPendingRequest() {
        return new PendingRequest();
    }

    /**
     * Create an instance of {@link PendingRentingRequestRequest }
     * 
     */
    public PendingRentingRequestRequest createPendingRentingRequestRequest() {
        return new PendingRentingRequestRequest();
    }

    /**
     * Create an instance of {@link UpdateRentingStatusRequest }
     * 
     */
    public UpdateRentingStatusRequest createUpdateRentingStatusRequest() {
        return new UpdateRentingStatusRequest();
    }

    /**
     * Create an instance of {@link UpdateRentingStatusResponse }
     * 
     */
    public UpdateRentingStatusResponse createUpdateRentingStatusResponse() {
        return new UpdateRentingStatusResponse();
    }

}
