<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://www.ftn.uns.ac.rs/advertisement" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ftn.uns.ac.rs/advertisement" targetNamespace="http://www.ftn.uns.ac.rs/advertisement">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ftn.uns.ac.rs/advertisement">
            <xs:element name="newAdvertisementRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="advertisement" type="tns:advertisement"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="newAdvertisementResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="advertisement" type="tns:advertisement"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="newPhotoRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="bytes" type="xs:base64Binary"/>
                        <xs:element name="path" type="xs:string"/>
                        <xs:element name="adId" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="commentRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ownerId" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="newPhotoResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:long"/>
                        <xs:element name="path" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="newRentingIntervalRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="rentingInterval" type="tns:rentingInterval"/>
                        <xs:element name="advertisementId" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="newRentingIntervalResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="rentingInterval" type="tns:rentingInterval"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="commentResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="comments" nillable="true" type="tns:comment"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="advertisement">
                <xs:sequence>
                    <xs:element name="id" type="xs:long"/>
                    <xs:element name="price" type="xs:double"/>
                    <xs:element name="kilometersPerDayLimit" type="xs:int"/>
                    <xs:element name="collisionDamageWaiver" type="xs:boolean"/>
                    <xs:element name="rating" type="xs:double"/>
                    <xs:element name="description" type="xs:string"/>
                    <xs:element name="location" type="xs:string"/>
                    <xs:element name="vehicle" type="tns:vehicle"/>
                    <xs:element name="ownerId" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="vehicle">
                <xs:sequence>
                    <xs:element name="id" type="xs:long"/>
                    <xs:element name="kilometersTraveled" type="xs:int"/>
                    <xs:element name="childSeatNumber" type="xs:int"/>
                    <xs:element name="hasAndroid" type="xs:boolean"/>
                    <xs:element name="fuelTypeId" type="xs:long"/>
                    <xs:element name="gearboxTypeId" type="xs:long"/>
                    <xs:element name="vehicleClassId" type="xs:long"/>
                    <xs:element name="modelId" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="rentingInterval">
                <xs:sequence>
                    <xs:element name="id" type="xs:long"/>
                    <xs:element name="startDate" type="xs:dateTime"/>
                    <xs:element name="endDate" type="xs:dateTime"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="comment">
                <xs:sequence>
                    <xs:element name="id" type="xs:long"/>
                    <xs:element name="title" type="xs:string"/>
                    <xs:element name="content" type="xs:string"/>
                    <xs:element name="allowed" type="xs:boolean"/>
                    <xs:element name="userId" type="xs:long"/>
                    <xs:element name="advertisementId" type="xs:long"/>
                    <xs:element name="rentingRequestId" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="newRentingIntervalRequest">
        <wsdl:part element="tns:newRentingIntervalRequest" name="newRentingIntervalRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="newPhotoResponse">
        <wsdl:part element="tns:newPhotoResponse" name="newPhotoResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="commentResponse">
        <wsdl:part element="tns:commentResponse" name="commentResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="newAdvertisementResponse">
        <wsdl:part element="tns:newAdvertisementResponse" name="newAdvertisementResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="newPhotoRequest">
        <wsdl:part element="tns:newPhotoRequest" name="newPhotoRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="newRentingIntervalResponse">
        <wsdl:part element="tns:newRentingIntervalResponse" name="newRentingIntervalResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="newAdvertisementRequest">
        <wsdl:part element="tns:newAdvertisementRequest" name="newAdvertisementRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="commentRequest">
        <wsdl:part element="tns:commentRequest" name="commentRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="AdvertisementPort">
        <wsdl:operation name="newRentingInterval">
            <wsdl:input message="tns:newRentingIntervalRequest" name="newRentingIntervalRequest"> </wsdl:input>
            <wsdl:output message="tns:newRentingIntervalResponse" name="newRentingIntervalResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="newPhoto">
            <wsdl:input message="tns:newPhotoRequest" name="newPhotoRequest"> </wsdl:input>
            <wsdl:output message="tns:newPhotoResponse" name="newPhotoResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="comment">
            <wsdl:input message="tns:commentRequest" name="commentRequest"> </wsdl:input>
            <wsdl:output message="tns:commentResponse" name="commentResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="newAdvertisement">
            <wsdl:input message="tns:newAdvertisementRequest" name="newAdvertisementRequest"> </wsdl:input>
            <wsdl:output message="tns:newAdvertisementResponse" name="newAdvertisementResponse"> </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AdvertisementPortSoap11" type="tns:AdvertisementPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="newRentingInterval">
            <soap:operation soapAction=""/>
            <wsdl:input name="newRentingIntervalRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="newRentingIntervalResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="newPhoto">
            <soap:operation soapAction=""/>
            <wsdl:input name="newPhotoRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="newPhotoResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="comment">
            <soap:operation soapAction=""/>
            <wsdl:input name="commentRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="commentResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="newAdvertisement">
            <soap:operation soapAction=""/>
            <wsdl:input name="newAdvertisementRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="newAdvertisementResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AdvertisementPortService">
        <wsdl:port binding="tns:AdvertisementPortSoap11" name="AdvertisementPortSoap11">
            <soap:address location="http://localhost:8081/ws"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>