<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://www.ftn.uns.ac.rs/renting" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ftn.uns.ac.rs/renting" targetNamespace="http://www.ftn.uns.ac.rs/renting">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ftn.uns.ac.rs/renting">
            <!--  Getter for finished renting requests on agent-app  -->
            <xs:element name="getFinishedRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getFinishedResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="finishedRequests" nillable="true" type="tns:finishedRequest"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="finishedRequest">
                <xs:sequence>
                    <xs:element name="requestId" type="xs:long"/>
                    <xs:element name="startDate" type="xs:dateTime"/>
                    <xs:element name="endDate" type="xs:dateTime"/>
                    <xs:element name="advertisementId" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <!--  Renting report creation  -->
            <xs:element name="compileReportRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="kilometersTraveled" type="xs:int"/>
                        <xs:element name="content" type="xs:string"/>
                        <xs:element name="requestID" type="xs:long"/>
                        <xs:element name="advertisementID" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="compileReportResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="kilometersTraveled" type="xs:int"/>
                        <xs:element name="content" type="xs:string"/>
                        <xs:element name="requestID" type="xs:long"/>
                        <xs:element name="advertisementID" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="pendingRentingRequestResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="pendingRequests" nillable="true" type="tns:pendingRequest"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:complexType name="pendingRequest">
                <xs:sequence>
                    <xs:element name="id" type="xs:long"/>
                    <xs:element name="startDate" type="xs:dateTime"/>
                    <xs:element name="endDate" type="xs:dateTime"/>
                    <xs:element name="senderId" type="xs:long"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="advertisementIds" nillable="true" type="xs:long"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="pendingRentingRequestRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="updateRentingStatusRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:long"/>
                        <xs:element name="status" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="updateRentingStatusResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:long"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="compileReportResponse">
        <wsdl:part element="tns:compileReportResponse" name="compileReportResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="updateRentingStatusRequest">
        <wsdl:part element="tns:updateRentingStatusRequest" name="updateRentingStatusRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="updateRentingStatusResponse">
        <wsdl:part element="tns:updateRentingStatusResponse" name="updateRentingStatusResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="getFinishedResponse">
        <wsdl:part element="tns:getFinishedResponse" name="getFinishedResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="pendingRentingRequestResponse">
        <wsdl:part element="tns:pendingRentingRequestResponse" name="pendingRentingRequestResponse"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="compileReportRequest">
        <wsdl:part element="tns:compileReportRequest" name="compileReportRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="pendingRentingRequestRequest">
        <wsdl:part element="tns:pendingRentingRequestRequest" name="pendingRentingRequestRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:message name="getFinishedRequest">
        <wsdl:part element="tns:getFinishedRequest" name="getFinishedRequest"> </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="RentingPort">
        <wsdl:operation name="compileReport">
            <wsdl:input message="tns:compileReportRequest" name="compileReportRequest"> </wsdl:input>
            <wsdl:output message="tns:compileReportResponse" name="compileReportResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="updateRentingStatus">
            <wsdl:input message="tns:updateRentingStatusRequest" name="updateRentingStatusRequest"> </wsdl:input>
            <wsdl:output message="tns:updateRentingStatusResponse" name="updateRentingStatusResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getFinished">
            <wsdl:input message="tns:getFinishedRequest" name="getFinishedRequest"> </wsdl:input>
            <wsdl:output message="tns:getFinishedResponse" name="getFinishedResponse"> </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="pendingRentingRequest">
            <wsdl:input message="tns:pendingRentingRequestRequest" name="pendingRentingRequestRequest"> </wsdl:input>
            <wsdl:output message="tns:pendingRentingRequestResponse" name="pendingRentingRequestResponse"> </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RentingPortSoap11" type="tns:RentingPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="compileReport">
            <soap:operation soapAction=""/>
            <wsdl:input name="compileReportRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="compileReportResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="updateRentingStatus">
            <soap:operation soapAction=""/>
            <wsdl:input name="updateRentingStatusRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="updateRentingStatusResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getFinished">
            <soap:operation soapAction=""/>
            <wsdl:input name="getFinishedRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getFinishedResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="pendingRentingRequest">
            <soap:operation soapAction=""/>
            <wsdl:input name="pendingRentingRequestRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="pendingRentingRequestResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RentingPortService">
        <wsdl:port binding="tns:RentingPortSoap11" name="RentingPortSoap11">
            <soap:address location="http://192.168.1.249:8086/ws"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>