//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.22 at 11:15:46 PM CEST 
//


package rs.ac.uns.ftn.renting;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.renting package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.renting
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFinishedResponse }
     * 
     */
    public GetFinishedResponse createGetFinishedResponse() {
        return new GetFinishedResponse();
    }

    /**
     * Create an instance of {@link FinishedRequest }
     * 
     */
    public FinishedRequest createFinishedRequest() {
        return new FinishedRequest();
    }

    /**
     * Create an instance of {@link CompileReportResponse }
     * 
     */
    public CompileReportResponse createCompileReportResponse() {
        return new CompileReportResponse();
    }

    /**
     * Create an instance of {@link GetFinishedRequest }
     * 
     */
    public GetFinishedRequest createGetFinishedRequest() {
        return new GetFinishedRequest();
    }

    /**
     * Create an instance of {@link CompileReportRequest }
     * 
     */
    public CompileReportRequest createCompileReportRequest() {
        return new CompileReportRequest();
    }

}
